Sharable cipher design
uclaacm/cipher-salad pull request #41
Opened 2020-10-01 04:41 UTC by rachelli99

restructured the layout for crack cipher

2020-10-01 04:43 UTC, malsf21 commented
Hey Rachel, glad you're back with us! Hm, I think you're still tripping up a few ESlint errors - can you fix those first @rachelli99?

2020-10-01 23:23 UTC, krashanoff requested changes
Hey Rachel! Thanks a ton for tackling this issue - I know it is rather chunky.

I really appreciated all the animations that were added in to the process, and *loved* the animation you used to explain the cipher shifting process. Along with the spacing and dividers, things are looking much cleaner. This said, there are still a good many details that need to be tackled. They are mostly small things like ensuring that the width of the container doesn't change, or that the page doesn't flash on cipher load.

I have left code-specific comments in the thread attached to this review, but here are the more general ones. I can provide specific points in the code to change to address them upon request:

## General

It would be nice to use a container with a minimum or set width to prevent the weird changes in container width that we see when inputting text. Take a look at the below screenshots for an example:

![image](https://user-images.githubusercontent.com/7704542/94872535-b4385080-0401-11eb-8edf-21d8f75a3866.png)

![image](https://user-images.githubusercontent.com/7704542/94872547-bd292200-0401-11eb-8396-b5eeeb09c2b1.png)

Notice how the width changes? We can prevent this by keeping the inner container to a wide minimum width:

```css
.cipher-container {
    min-width: 90%;
}
```

## Can you solve my cipher?

![image](https://user-images.githubusercontent.com/7704542/94872240-f8772100-0400-11eb-9643-c0e2315d8164.png)

I'd like for the animation here to play out a single time, then stop to reveal the entire process to the user. In its current state, it gets the point across, but it can be a little hard to follow. On a more specific note, I think that the divider should have a little bit more spacing to keep it from colliding with the letters.

In this same section, when we input the link for the cipher, the entire page flashes.

After we paste it, I think that we should be able to just press "Load" and then immediately have the cipher solving portion come up, rather than manually clicking the "Next" that appears.

## Let's get cracking!

![image](https://user-images.githubusercontent.com/7704542/94872418-64f22000-0401-11eb-88ce-af5cd4135491.png)

It would be nice to see the decoded text somewhere as well so that way the message gets through to the user :+1:

Sorry for the huge review! Let me know if you have any questions.

2020-10-01 23:23 UTC, krashanoff commented on src/Components/ShareCipher/Congrats.js
> +    let ciphertext = props.cipher[0];             // current guess at the deciphered message
Since our props don't change within the scope of the component, these can be `const`!

2020-10-01 23:23 UTC, krashanoff commented on src/Components/ShareCipher/Congrats.js
> +            <h1 className='title is-size-2 underline mt-4'>Are you the new crack master?</h1>
A small change of wording would be nice here. "Crack master" is probably not the term we want to throw around with kids 😅

2020-10-01 23:23 UTC, krashanoff commented on src/Components/ShareCipher/Congrats.js
> +                    </Anime>
This is rather picky but I'd rather you indent this properly. It helps significantly with readability. If you want to automate this, [there are linters that can do this](https://prettier.io/docs/en/precommit.html)

```suggestion
                <section className='share-section'>
                    <Anime 
                        easing="linear"
                        delay='100' 
                        opacity={['0%','100%']}
                        duration="1000"
                    >
                        <FontAwesomeIcon icon={faGraduationCap} alt='key' size="6x" color="#FFB800" />
                        <p className='is-size-3 mb-5'>Congratulations! </p>
                    </Anime>
```

2020-10-01 23:23 UTC, krashanoff commented on src/Components/ShareCipher/CrackCipher.js
> +    if(firstTimeLoad){  // fade in effect on first time load, instead of everytime the wheel turns
This is a *really* big if/else statement. Instead of using this, how about trying something a little more compact?

Here's an example: here, I do the same thing: use a state variable to track whether the page has been loaded in already. However, instead of using an if/else with code duplication, I instead use an if/else before the render to control whether the `<Anime />` tags do anything useful.

```js
import React, { useState } from 'react';
import Anime from 'react-anime';

export default function App() {
  const [ hasPlayed, setHasPlayed ] = useState(false);  // Tracking animation plays.
  const [ dummyEvent, setDummyEvent ] = useState(true);    // Dummy event to force rerenders.

  return (
    <div className="App">

      {/* Use a ternary to control whether the animation does anything useful. */}
      <Anime opacity={!hasPlayed ? [0,1] : [1]} duration={5000}>
        <h1>Hi</h1>
      </Anime>

      <button onClick={() => setDummyEvent(!dummyEvent)}>This will play it again</button>
      <button onClick={() => setHasPlayed(true)}>This will stop it from animating</button>
    </div>
  );
}
```

2020-10-01 23:23 UTC, krashanoff commented on src/Components/ShareCipher/shareCipher.scss
> +}
Remember to set this container to `display: flex;`!

2020-10-01 23:23 UTC, krashanoff commented on src/Components/ShareCipher/SolveCipher.js
> +                                <div class="column"></div>
How come we have these extra columns here? If we are using them for formatting, it may pay dividends to simply leave them out and let flexbox do its thing.

2020-10-01 23:23 UTC, krashanoff commented on src/Components/ShareCipher/SolveCipher.js
> +                                </div>
Two things:
1. Formatting here will help for readability
2. I noticed a lot of duplication here. Instead of creating the same lines of code over and over again, let's leverage JSX to generate them flexibly. Here's an example:

```js
import React from 'react';
import Anime from 'react-anime';

// Generates some animated components from an input string.
// Each word is transformed into an h2 tag wrapped with an
// <Anime /> component.
export default function App() {
  // create some array to work with.
  const someArr = 'A long string of words split into headers'.split(' ');

  return (
    <div>
      {/* for each word, map it to our desired template. */}
      {
        someArr.map(word => (
          <Anime opacity={[0,1]} duration={5000}>
            <h2 className='word'>{word}</h2>
          </Anime>
        ))
      }
    </div>
  );
}
```

This renders:

![image](https://user-images.githubusercontent.com/7704542/94872147-b057fe80-0400-11eb-81e1-8efdb5375b76.png)

2020-10-01 23:23 UTC, krashanoff commented on src/Components/ShareCipher/SolveCipher.js
> +                    <Anime easing="linear" duration="700" loop={false} opacity={['0%','100%']} >
You will likely need to repeat what you did in your crackCipher component to track whether this animation has played out, otherwise you will get flashing when you shift the wheel.

2020-10-11 22:25 UTC, krashanoff approved these changes
Hey Rachel, sorry for the delay on this PR. Thank you for addressing my feedback, great work! I think I'd like to merge this real quick just to get the visuals up to snuff. Some comments on things that we should change going forward:
* The appearance on mobile is a little strange when solving a cipher.
* There's a slight visual bug I encountered on the `SolveCipher` animation. On load, the component flashes all components for a split second.
* We could clean up the styles.

Aside from this, things are looking much more conducive to the vision I had setting out with the cipher project. Nice work Rachel!

2020-10-11 22:25 UTC, krashanoff commented on src/Components/ShareCipher/shareCipher.scss
> +    max-width: 60vw;
```suggestion
    width: 60vw;
```

You can use `width: 60vw` here :+1:

2020-10-13 05:17 UTC, krashanoff commented
Going to ping @rachelli99 one more time for confirmation. Otherwise, will merge for sake of time.

2020-10-13 12:16 UTC, rachelli99 commented
> Going to ping @rachelli99 one more time for confirmation. Otherwise, will merge for sake of time.

Sounds good, feel free to merge it. I'll work on the other minor fixes as we go. Thanks for all the feedbacks and help!

2020-10-14 03:27 UTC, merged